-- =====================================================================
-- Enterprise AI Agent Hub — COMBINED MIGRATION (migrate.sql)
-- =====================================================================
-- Generated by concatenating the 16 migration files in dependency order.
-- Paste this whole file into the Supabase SQL Editor and run once on a
-- FRESH project to build the entire database structure.
--
-- This file does NOT include:
--   * seed.sql            (demo Northwind data — run separately only if wanted)
--   * accounts_rollback.sql (teardown/reversal — emergency use only)
--
-- Run order encoded below (see each STEP banner):
--   1 schema  2 provider_keys  3 connections  4 apps  5 apps_profile
--   6 agent_access  7 logos  8 agent_runs  9 mission  10 governance_kb
--   11 knowledge_docs  12 rag  13 rag_incremental  14 deletes
--   15 accounts  16 accounts_fix_recursion
-- =====================================================================


-- #####################################################################
-- STEP 01 / 16 — schema.sql
-- #####################################################################

-- =====================================================================
-- Enterprise AI Agent Hub — Database Schema
-- Target: Supabase (PostgreSQL 15+)
-- Run order: schema.sql  ->  seed.sql
--
-- Design notes:
--   * Multi-tenant by organization_id. Every business table carries it.
--   * RBAC enforced via profiles.app_role + org_members.org_role and RLS.
--   * Immutable audit trail (audit_logs) written by triggers.
--   * Agent change history kept in agent_versions (point-in-time snapshots).
--   * Human-in-the-loop governance via governance_requests + approvals.
-- =====================================================================

create extension if not exists "pgcrypto";   -- gen_random_uuid()

-- ---------------------------------------------------------------------
-- ENUM TYPES
-- ---------------------------------------------------------------------
do $$ begin
  create type app_role as enum ('admin', 'builder', 'reviewer', 'member');
exception when duplicate_object then null; end $$;

do $$ begin
  create type org_role as enum ('owner', 'manager', 'staff');
exception when duplicate_object then null; end $$;

do $$ begin
  create type agent_status as enum ('draft', 'in_review', 'published', 'deprecated', 'blocked');
exception when duplicate_object then null; end $$;

do $$ begin
  create type risk_tier as enum ('low', 'moderate', 'high', 'restricted');
exception when duplicate_object then null; end $$;

do $$ begin
  create type request_kind as enum ('publish', 'version', 'access', 'decommission', 'policy_exception');
exception when duplicate_object then null; end $$;

do $$ begin
  create type request_status as enum ('open', 'approved', 'rejected', 'changes_requested', 'withdrawn');
exception when duplicate_object then null; end $$;

do $$ begin
  create type session_status as enum ('active', 'idle', 'closed', 'revoked');
exception when duplicate_object then null; end $$;

-- =====================================================================
-- TABLE 1 — organizations
-- =====================================================================
create table if not exists public.organizations (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  slug            text not null unique,
  industry        text,
  size_band       text,                       -- e.g. '1-50','51-200','201-1000','1000+'
  hq_region       text,
  data_residency  text default 'us',
  governance_mode text default 'standard',    -- 'standard' | 'strict'
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- =====================================================================
-- TABLE 2 — profiles  (1:1 with auth.users)
-- =====================================================================
create table if not exists public.profiles (
  id              uuid primary key references auth.users(id) on delete cascade,
  email           text,
  full_name       text,
  app_role        app_role not null default 'member',
  default_org_id  uuid references public.organizations(id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- =====================================================================
-- TABLE 3 — org_members  (membership + per-org role)
-- =====================================================================
create table if not exists public.org_members (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id         uuid not null references public.profiles(id) on delete cascade,
  org_role        org_role not null default 'staff',
  created_at      timestamptz not null default now(),
  unique (organization_id, user_id)
);
create index if not exists idx_org_members_user on public.org_members(user_id);
create index if not exists idx_org_members_org  on public.org_members(organization_id);

-- =====================================================================
-- TABLE 4 — intake_submissions  (corporate + role intake)
-- =====================================================================
create table if not exists public.intake_submissions (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  intake_type     text not null check (intake_type in ('corporate','role')),
  submitted_by    uuid references public.profiles(id) on delete set null,
  payload         jsonb not null default '{}'::jsonb,
  status          text not null default 'received',  -- received | processed | archived
  created_at      timestamptz not null default now()
);
create index if not exists idx_intake_org on public.intake_submissions(organization_id);

-- =====================================================================
-- TABLE 5 — roles  (the jobs/functions agents are matched to)
-- =====================================================================
create table if not exists public.roles (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  title           text not null,
  department      text,
  description     text,
  responsibilities jsonb not null default '[]'::jsonb,   -- string[]
  tools_used      jsonb not null default '[]'::jsonb,     -- string[]
  intake_id       uuid references public.intake_submissions(id) on delete set null,
  created_at      timestamptz not null default now()
);
create index if not exists idx_roles_org on public.roles(organization_id);

-- =====================================================================
-- TABLE 6 — agents  (catalog entry; published version pointer)
-- =====================================================================
create table if not exists public.agents (
  id               uuid primary key default gen_random_uuid(),
  organization_id  uuid not null references public.organizations(id) on delete cascade,
  slug             text not null,
  name             text not null,
  summary          text,
  category         text,                        -- e.g. 'Finance','HR','Support'
  status           agent_status not null default 'draft',
  risk             risk_tier not null default 'low',
  owner_id         uuid references public.profiles(id) on delete set null,
  current_version  int not null default 1,
  tags             jsonb not null default '[]'::jsonb,
  capabilities     jsonb not null default '[]'::jsonb,    -- string[]
  tools            jsonb not null default '[]'::jsonb,    -- string[] (internal tools/skills)
  connectors       jsonb not null default '[]'::jsonb,    -- string[] (connector keys; execution wired later)
  avg_rating       numeric(3,2) default 0,
  deployments      int default 0,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (organization_id, slug)
);
create index if not exists idx_agents_org    on public.agents(organization_id);
create index if not exists idx_agents_status on public.agents(status);

-- =====================================================================
-- TABLE 7 — agent_versions  (immutable point-in-time snapshots)
-- =====================================================================
create table if not exists public.agent_versions (
  id              uuid primary key default gen_random_uuid(),
  agent_id        uuid not null references public.agents(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  version         int not null,
  status          agent_status not null default 'draft',
  system_prompt   text,
  model           text default 'gpt-4o-mini',
  temperature     numeric(3,2) default 0.30,
  config          jsonb not null default '{}'::jsonb,   -- tools, guardrails, etc.
  changelog       text,
  created_by      uuid references public.profiles(id) on delete set null,
  created_at      timestamptz not null default now(),
  unique (agent_id, version)
);
create index if not exists idx_versions_agent on public.agent_versions(agent_id);

-- =====================================================================
-- TABLE 8 — recommendations  (role -> ranked agent matches)
-- =====================================================================
create table if not exists public.recommendations (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  role_id         uuid references public.roles(id) on delete cascade,
  agent_id        uuid references public.agents(id) on delete set null,
  rank            int not null default 1,
  match_score     numeric(4,3) not null default 0,       -- 0..1
  rationale       text,
  generated_by    text default 'openai',                 -- 'openai' | 'heuristic'
  created_at      timestamptz not null default now()
);
create index if not exists idx_recs_role on public.recommendations(role_id);

-- =====================================================================
-- TABLE 9 — sessions  (secure runtime sessions against an agent)
-- =====================================================================
create table if not exists public.sessions (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  agent_id        uuid not null references public.agents(id) on delete cascade,
  user_id         uuid references public.profiles(id) on delete set null,
  status          session_status not null default 'active',
  ip_hash         text,                                   -- store hash, never raw IP
  user_agent      text,
  started_at      timestamptz not null default now(),
  last_active_at  timestamptz not null default now(),
  closed_at       timestamptz,
  revoked_reason  text
);
create index if not exists idx_sessions_org   on public.sessions(organization_id);
create index if not exists idx_sessions_agent on public.sessions(agent_id);

-- =====================================================================
-- TABLE 10 — session_messages  (per-turn transcript)
-- =====================================================================
create table if not exists public.session_messages (
  id              uuid primary key default gen_random_uuid(),
  session_id      uuid not null references public.sessions(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  role            text not null check (role in ('user','assistant','system','tool')),
  content         text,
  tokens          int default 0,
  created_at      timestamptz not null default now()
);
create index if not exists idx_msgs_session on public.session_messages(session_id);

-- =====================================================================
-- TABLE 11 — governance_requests  (the review queue)
-- =====================================================================
create table if not exists public.governance_requests (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  agent_id        uuid references public.agents(id) on delete cascade,
  version_id      uuid references public.agent_versions(id) on delete set null,
  kind            request_kind not null,
  status          request_status not null default 'open',
  title           text not null,
  detail          text,
  risk            risk_tier not null default 'low',
  requested_by    uuid references public.profiles(id) on delete set null,
  created_at      timestamptz not null default now(),
  resolved_at     timestamptz
);
create index if not exists idx_gov_org    on public.governance_requests(organization_id);
create index if not exists idx_gov_status on public.governance_requests(status);

-- =====================================================================
-- TABLE 12 — approvals  (decisions on governance_requests)
-- =====================================================================
create table if not exists public.approvals (
  id              uuid primary key default gen_random_uuid(),
  request_id      uuid not null references public.governance_requests(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  reviewer_id     uuid references public.profiles(id) on delete set null,
  decision        request_status not null,   -- approved | rejected | changes_requested
  note            text,
  created_at      timestamptz not null default now()
);
create index if not exists idx_approvals_request on public.approvals(request_id);

-- =====================================================================
-- TABLE 13 — audit_logs  (append-only; written by triggers)
-- =====================================================================
create table if not exists public.audit_logs (
  id              bigint generated always as identity primary key,
  organization_id uuid,
  actor_id        uuid,
  action          text not null,             -- INSERT | UPDATE | DELETE
  entity          text not null,             -- table name
  entity_id       text,
  diff            jsonb,
  created_at      timestamptz not null default now()
);
create index if not exists idx_audit_org    on public.audit_logs(organization_id);
create index if not exists idx_audit_entity on public.audit_logs(entity, entity_id);

-- =====================================================================
-- TABLE 14 — analytics_events  (usage telemetry)
-- =====================================================================
create table if not exists public.analytics_events (
  id              bigint generated always as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  agent_id        uuid references public.agents(id) on delete set null,
  user_id         uuid references public.profiles(id) on delete set null,
  event_type      text not null,             -- 'session_start','message','recommendation_view','publish'...
  properties      jsonb not null default '{}'::jsonb,
  created_at      timestamptz not null default now()
);
create index if not exists idx_events_org  on public.analytics_events(organization_id);
create index if not exists idx_events_type on public.analytics_events(event_type);
create index if not exists idx_events_time on public.analytics_events(created_at);

-- =====================================================================
-- HELPER FUNCTIONS (used by RLS policies)
-- =====================================================================

-- Is the current user a member of this org?
create or replace function public.is_org_member(org uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.org_members m
    where m.organization_id = org and m.user_id = auth.uid()
  );
$$;

-- Current user's app_role
create or replace function public.current_app_role()
returns app_role language sql stable security definer set search_path = public as $$
  select app_role from public.profiles where id = auth.uid();
$$;

-- Does the current user hold a reviewer/admin app_role?
create or replace function public.can_review()
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce(public.current_app_role() in ('admin','reviewer'), false);
$$;

-- =====================================================================
-- AUDIT TRIGGER  (writes to audit_logs on write to governed tables)
-- =====================================================================
create or replace function public.fn_audit()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  org uuid;
  eid text;
begin
  org := coalesce(
    (case when tg_op = 'DELETE' then (to_jsonb(old)->>'organization_id')
          else (to_jsonb(new)->>'organization_id') end)::uuid,
    null);
  eid := coalesce(
    (case when tg_op = 'DELETE' then (to_jsonb(old)->>'id')
          else (to_jsonb(new)->>'id') end),
    null);

  insert into public.audit_logs(organization_id, actor_id, action, entity, entity_id, diff)
  values (
    org,
    auth.uid(),
    tg_op,
    tg_table_name,
    eid,
    case tg_op
      when 'DELETE' then jsonb_build_object('old', to_jsonb(old))
      when 'INSERT' then jsonb_build_object('new', to_jsonb(new))
      else jsonb_build_object('old', to_jsonb(old), 'new', to_jsonb(new))
    end
  );
  return coalesce(new, old);
end $$;

drop trigger if exists trg_audit_agents on public.agents;
create trigger trg_audit_agents
  after insert or update or delete on public.agents
  for each row execute function public.fn_audit();

drop trigger if exists trg_audit_versions on public.agent_versions;
create trigger trg_audit_versions
  after insert or update or delete on public.agent_versions
  for each row execute function public.fn_audit();

drop trigger if exists trg_audit_gov on public.governance_requests;
create trigger trg_audit_gov
  after insert or update or delete on public.governance_requests
  for each row execute function public.fn_audit();

drop trigger if exists trg_audit_approvals on public.approvals;
create trigger trg_audit_approvals
  after insert or update or delete on public.approvals
  for each row execute function public.fn_audit();

-- =====================================================================
-- updated_at maintenance
-- =====================================================================
create or replace function public.fn_touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at := now(); return new; end $$;

drop trigger if exists trg_touch_agents on public.agents;
create trigger trg_touch_agents before update on public.agents
  for each row execute function public.fn_touch_updated_at();

drop trigger if exists trg_touch_orgs on public.organizations;
create trigger trg_touch_orgs before update on public.organizations
  for each row execute function public.fn_touch_updated_at();

-- =====================================================================
-- ROW LEVEL SECURITY
-- =====================================================================
alter table public.organizations      enable row level security;
alter table public.profiles            enable row level security;
alter table public.org_members         enable row level security;
alter table public.intake_submissions  enable row level security;
alter table public.roles               enable row level security;
alter table public.agents              enable row level security;
alter table public.agent_versions      enable row level security;
alter table public.recommendations     enable row level security;
alter table public.sessions            enable row level security;
alter table public.session_messages    enable row level security;
alter table public.governance_requests enable row level security;
alter table public.approvals           enable row level security;
alter table public.audit_logs          enable row level security;
alter table public.analytics_events    enable row level security;

-- profiles: a user can see/update only their own profile
drop policy if exists p_profiles_self on public.profiles;
create policy p_profiles_self on public.profiles
  for all using (id = auth.uid()) with check (id = auth.uid());

-- organizations: members can read; only admins may write
drop policy if exists p_org_read on public.organizations;
create policy p_org_read on public.organizations
  for select using (public.is_org_member(id));
drop policy if exists p_org_write on public.organizations;
create policy p_org_write on public.organizations
  for update using (public.is_org_member(id) and public.current_app_role() = 'admin');

-- org_members: members can read membership of their orgs
drop policy if exists p_members_read on public.org_members;
create policy p_members_read on public.org_members
  for select using (public.is_org_member(organization_id));

-- Generic per-org read for tenant tables
drop policy if exists p_intake_rw on public.intake_submissions;
create policy p_intake_rw on public.intake_submissions
  for all using (public.is_org_member(organization_id))
  with check (public.is_org_member(organization_id));

drop policy if exists p_roles_rw on public.roles;
create policy p_roles_rw on public.roles
  for all using (public.is_org_member(organization_id))
  with check (public.is_org_member(organization_id));

-- agents: members read; builders/admins write (RBAC)
drop policy if exists p_agents_read on public.agents;
create policy p_agents_read on public.agents
  for select using (public.is_org_member(organization_id));
drop policy if exists p_agents_write on public.agents;
create policy p_agents_write on public.agents
  for all using (
    public.is_org_member(organization_id)
    and public.current_app_role() in ('admin','builder')
  ) with check (
    public.is_org_member(organization_id)
    and public.current_app_role() in ('admin','builder')
  );

drop policy if exists p_versions_read on public.agent_versions;
create policy p_versions_read on public.agent_versions
  for select using (public.is_org_member(organization_id));
drop policy if exists p_versions_write on public.agent_versions;
create policy p_versions_write on public.agent_versions
  for all using (
    public.is_org_member(organization_id)
    and public.current_app_role() in ('admin','builder')
  ) with check (
    public.is_org_member(organization_id)
    and public.current_app_role() in ('admin','builder')
  );

drop policy if exists p_recs_rw on public.recommendations;
create policy p_recs_rw on public.recommendations
  for all using (public.is_org_member(organization_id))
  with check (public.is_org_member(organization_id));

-- sessions: a user sees their own sessions; reviewers/admins see all org sessions
drop policy if exists p_sessions_read on public.sessions;
create policy p_sessions_read on public.sessions
  for select using (
    public.is_org_member(organization_id)
    and (user_id = auth.uid() or public.can_review())
  );
drop policy if exists p_sessions_write on public.sessions;
create policy p_sessions_write on public.sessions
  for all using (public.is_org_member(organization_id) and user_id = auth.uid())
  with check (public.is_org_member(organization_id) and user_id = auth.uid());

drop policy if exists p_msgs_rw on public.session_messages;
create policy p_msgs_rw on public.session_messages
  for all using (
    public.is_org_member(organization_id)
    and exists (
      select 1 from public.sessions s
      where s.id = session_id
        and (s.user_id = auth.uid() or public.can_review())
    )
  ) with check (public.is_org_member(organization_id));

-- governance: members read; reviewers/admins write
drop policy if exists p_gov_read on public.governance_requests;
create policy p_gov_read on public.governance_requests
  for select using (public.is_org_member(organization_id));
drop policy if exists p_gov_insert on public.governance_requests;
create policy p_gov_insert on public.governance_requests
  for insert with check (public.is_org_member(organization_id));
drop policy if exists p_gov_update on public.governance_requests;
create policy p_gov_update on public.governance_requests
  for update using (public.is_org_member(organization_id) and public.can_review());

drop policy if exists p_approvals_read on public.approvals;
create policy p_approvals_read on public.approvals
  for select using (public.is_org_member(organization_id));
drop policy if exists p_approvals_write on public.approvals;
create policy p_approvals_write on public.approvals
  for insert with check (public.is_org_member(organization_id) and public.can_review());

-- audit_logs: read-only to members; no client writes (trigger-only via definer)
drop policy if exists p_audit_read on public.audit_logs;
create policy p_audit_read on public.audit_logs
  for select using (public.is_org_member(organization_id));

drop policy if exists p_events_rw on public.analytics_events;
create policy p_events_rw on public.analytics_events
  for all using (public.is_org_member(organization_id))
  with check (public.is_org_member(organization_id));

-- =====================================================================
-- Convenience view: agent catalog with owner name (for the Hub)
-- =====================================================================
-- DROP first, then create: this view uses `a.*`, so when a later migration adds
-- a column to agents (e.g. agent_access.sql adds `visibility`), the column order
-- shifts and `create or replace view` fails with 42P16 ("cannot change name of
-- view column ..."). Dropping sidesteps that on re-run. CASCADE is safe — nothing
-- depends on this convenience view.
drop view if exists public.v_agent_catalog cascade;
create view public.v_agent_catalog as
  select a.*, p.full_name as owner_name
  from public.agents a
  left join public.profiles p on p.id = a.owner_id;

-- =====================================================================
-- AUTH INTEGRATION  (added for the live app)
--   * Auto-create a profiles row whenever a Supabase Auth user is created
--     (sign-up OR admin invite), so foreign keys resolve without seed data.
--   * Prevent ordinary users from escalating their own app_role: only the
--     service role (auth.uid() IS NULL) may change it. The provider/admin is
--     promoted server-side via the SUPABASE_SERVICE_ROLE_KEY.
--   * Let users in the same organization read each other's basic profile, so
--     the Library can display "who created this agent".
-- =====================================================================

-- Create the profile when an auth user appears.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, full_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1))
  )
  on conflict (id) do update
    set email = excluded.email,
        full_name = coalesce(public.profiles.full_name, excluded.full_name);
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Block self-service role escalation. Service-role writes have auth.uid() = NULL
-- and are allowed (that is how the provider/admin gets promoted).
create or replace function public.fn_guard_profile_role()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is not null and new.app_role is distinct from old.app_role then
    new.app_role := old.app_role;   -- silently ignore the attempted change
  end if;
  return new;
end $$;

drop trigger if exists trg_guard_profile_role on public.profiles;
create trigger trg_guard_profile_role before update on public.profiles
  for each row execute function public.fn_guard_profile_role();

-- Does the current user share any organization with the target user?
-- SECURITY DEFINER so it does not recurse through org_members RLS.
create or replace function public.shares_org(target uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1
    from public.org_members a
    join public.org_members b on a.organization_id = b.organization_id
    where a.user_id = auth.uid() and b.user_id = target
  );
$$;

-- Broaden profile SELECT: yourself OR anyone in a shared org (read-only).
-- The existing p_profiles_self policy still governs writes.
drop policy if exists p_profiles_read_team on public.profiles;
create policy p_profiles_read_team on public.profiles
  for select using (id = auth.uid() or public.shares_org(id));

-- End of schema.sql


-- #####################################################################
-- STEP 02 / 16 — provider_keys.sql
-- #####################################################################

-- =====================================================================
-- Provider keys — per-tenant BYO API keys (BYOK)
-- Run AFTER schema.sql, in the Supabase SQL editor.
--
-- A company (org) may store its own AI provider key so its agent RUNS bill to
-- its own provider account instead of the shared platform key. The app encrypts
-- the key (AES-256-GCM, lib/crypto.ts) before it ever reaches this table — the
-- database only ever sees ciphertext plus a masked, non-secret hint.
--
-- TWO-LAYER PROTECTION for the secret:
--   1. RLS restricts every row to the org's OWNER (org_role = 'owner').
--   2. Column-level grants: the browser-facing Postgres roles (anon,
--      authenticated) are NOT granted SELECT on encrypted_key, so the ciphertext
--      cannot be read from the browser AT ALL — even an owner reading their own
--      row gets only the masked columns. The ciphertext is reachable solely via
--      the service role (server-side, lib/provider-keys.ts), which bypasses RLS.
-- =====================================================================

-- Is the current user an OWNER of this org? (mirrors is_org_member in schema.sql)
create or replace function public.is_org_owner(org uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.org_members m
    where m.organization_id = org
      and m.user_id = auth.uid()
      and m.org_role = 'owner'
  );
$$;

create table if not exists public.org_provider_keys (
  id               uuid primary key default gen_random_uuid(),
  organization_id  uuid not null references public.organizations(id) on delete cascade,
  provider         text not null check (provider in ('openai','anthropic','google')),
  encrypted_key    text not null,        -- AES-256-GCM ciphertext, NEVER exposed to a browser
  key_hint         text not null,        -- masked preview e.g. 'sk-a…3xQp' (safe, non-secret)
  model            text,                 -- optional per-tenant model override
  created_by       uuid references public.profiles(id) on delete set null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (organization_id, provider)     -- one key per provider per tenant
);
create index if not exists idx_provider_keys_org on public.org_provider_keys(organization_id);

alter table public.org_provider_keys enable row level security;

-- LAYER 1 — RLS: only an org OWNER may touch that org's provider keys.
drop policy if exists p_provider_keys_owner on public.org_provider_keys;
create policy p_provider_keys_owner on public.org_provider_keys
  for all using (public.is_org_owner(organization_id))
  with check (public.is_org_owner(organization_id));

-- LAYER 2 — column privileges: revoke everything from the browser roles, then
-- grant SELECT on the NON-SECRET columns only. encrypted_key is deliberately
-- omitted, so `select encrypted_key` (or `select *`) is denied for anon /
-- authenticated even on rows RLS would otherwise expose. Writes never go through
-- these roles — the app persists keys with the service role after an owner check.
revoke all on public.org_provider_keys from anon, authenticated;
grant select (id, organization_id, provider, key_hint, model, created_by, created_at, updated_at)
  on public.org_provider_keys to authenticated;

-- Service role (server-side, RLS-bypassing) keeps full access, incl. ciphertext.
grant all on public.org_provider_keys to service_role;

-- keep updated_at fresh (reuses the helper from schema.sql)
drop trigger if exists trg_touch_provider_keys on public.org_provider_keys;
create trigger trg_touch_provider_keys before update on public.org_provider_keys
  for each row execute function public.fn_touch_updated_at();

-- End of provider_keys.sql


-- #####################################################################
-- STEP 03 / 16 — connections.sql
-- #####################################################################

-- =====================================================================
-- Connections — per-user OAuth links to external mailboxes (Gmail, etc.)
-- Run AFTER schema.sql, in the Supabase SQL editor.
--
-- A connection belongs to ONE user (their own mailbox). Tokens are stored
-- encrypted by the app (AES-256-GCM) before they ever reach this table — the
-- database only ever sees ciphertext. RLS restricts every row to its owner.
-- =====================================================================

create table if not exists public.connections (
  id               uuid primary key default gen_random_uuid(),
  user_id          uuid not null references public.profiles(id) on delete cascade,
  organization_id  uuid references public.organizations(id) on delete set null,
  provider         text not null check (provider in ('google','microsoft')),
  account_email    text,
  access_token     text,                 -- encrypted
  refresh_token    text,                 -- encrypted
  token_expires_at timestamptz,
  scopes           text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (user_id, provider)
);
create index if not exists idx_connections_user on public.connections(user_id);

alter table public.connections enable row level security;

-- Owner-only access: a user can read/write only their own connections.
drop policy if exists p_connections_self on public.connections;
create policy p_connections_self on public.connections
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- keep updated_at fresh (reuses the helper from schema.sql)
drop trigger if exists trg_touch_connections on public.connections;
create trigger trg_touch_connections before update on public.connections
  for each row execute function public.fn_touch_updated_at();

-- End of connections.sql


-- #####################################################################
-- STEP 04 / 16 — apps.sql
-- #####################################################################

-- =====================================================================
-- "Apps" — registered, launchable links to existing tools (dashboards, etc.)
-- Run AFTER schema.sql, in the Supabase SQL editor.
--
-- An app is a much simpler sibling of an agent: a governed catalog entry with
-- a URL — no system prompt, no AI provider, no run logic. It mirrors the agents
-- pattern (per-org RLS isolation, owner attribution) and reuses the SAME
-- governance flow (governance_requests + approvals): a new app starts
-- 'in_review' and only becomes 'published' (launchable) after a reviewer approves.
-- =====================================================================

-- App lifecycle — same values as agent_status so the shared StatusBadge/types work.
do $$ begin
  create type app_status as enum ('draft','in_review','published','deprecated','blocked');
exception when duplicate_object then null; end $$;

create table if not exists public.apps (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name            text not null,
  url             text not null,                 -- external launch URL (http/https)
  description     text,
  category        text,
  status          app_status not null default 'in_review',
  product_owner   uuid references public.profiles(id) on delete set null,  -- attribution
  created_by      uuid references public.profiles(id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index if not exists idx_apps_org    on public.apps(organization_id);
create index if not exists idx_apps_status on public.apps(status);

-- Governance linkage: a governance_request can now target an agent OR an app.
alter table public.governance_requests
  add column if not exists app_id uuid references public.apps(id) on delete cascade;
create index if not exists idx_gov_app on public.governance_requests(app_id);

-- updated_at + audit trail (reuse the shared helpers/functions from schema.sql)
drop trigger if exists trg_touch_apps on public.apps;
create trigger trg_touch_apps before update on public.apps
  for each row execute function public.fn_touch_updated_at();

drop trigger if exists trg_audit_apps on public.apps;
create trigger trg_audit_apps
  after insert or update or delete on public.apps
  for each row execute function public.fn_audit();

-- RLS — mirrors agents exactly: members read; admins/builders write.
alter table public.apps enable row level security;

drop policy if exists p_apps_read on public.apps;
create policy p_apps_read on public.apps
  for select using (public.is_org_member(organization_id));

drop policy if exists p_apps_write on public.apps;
create policy p_apps_write on public.apps
  for all using (
    public.is_org_member(organization_id)
    and public.current_app_role() in ('admin','builder')
  ) with check (
    public.is_org_member(organization_id)
    and public.current_app_role() in ('admin','builder')
  );

-- End of apps.sql


-- #####################################################################
-- STEP 05 / 16 — apps_profile.sql
-- #####################################################################

-- =====================================================================
-- Richer app profile fields. Run AFTER apps.sql.
-- All nullable so existing apps are unaffected. "What it does" reuses the
-- existing apps.description column. status_label is descriptive/operational
-- metadata, SEPARATE from the governance status (in_review/published) that
-- still controls launchability.
-- =====================================================================

alter table public.apps add column if not exists primary_users text;
alter table public.apps add column if not exists key_features  text;
alter table public.apps add column if not exists data_inputs   text;
alter table public.apps add column if not exists status_label  text;

-- End of apps_profile.sql


-- #####################################################################
-- STEP 06 / 16 — agent_access.sql
-- #####################################################################

-- =====================================================================
-- Per-agent access control. Run AFTER schema.sql.
--
-- An agent is 'everyone' (all company members — current default) or 'restricted'
-- (only the owner + assigned users + company admins/owner). The restricted-aware
-- read policy below enforces BOTH catalog visibility AND run access in one place:
-- the run routes load the agent through RLS, so a hidden agent returns 404 and
-- cannot be run. Tenant isolation is unchanged (everything is is_org_member-scoped).
-- =====================================================================

alter table public.agents add column if not exists visibility text not null default 'everyone';
do $$ begin
  alter table public.agents add constraint agents_visibility_chk check (visibility in ('everyone','restricted'));
exception when duplicate_object then null; end $$;

create table if not exists public.agent_access (
  id              uuid primary key default gen_random_uuid(),
  agent_id        uuid not null references public.agents(id) on delete cascade,
  user_id         uuid not null references public.profiles(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  granted_by      uuid references public.profiles(id) on delete set null,
  created_at      timestamptz not null default now(),
  unique (agent_id, user_id)
);
create index if not exists idx_agent_access_agent on public.agent_access(agent_id);
create index if not exists idx_agent_access_user  on public.agent_access(user_id);

-- SECURITY DEFINER helpers — bypass RLS to avoid recursion (mirrors shares_org).
create or replace function public.is_agent_owner(a uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.agents ag where ag.id = a and ag.owner_id = auth.uid());
$$;

create or replace function public.has_agent_access(a uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.agent_access aa where aa.agent_id = a and aa.user_id = auth.uid());
$$;

-- Restricted-aware read: everyone-visible OR owner OR assigned OR company admin/owner.
drop policy if exists p_agents_read on public.agents;
create policy p_agents_read on public.agents
  for select using (
    public.is_org_member(organization_id)
    and (
      visibility = 'everyone'
      or owner_id = auth.uid()
      or public.has_agent_access(id)
      or public.current_app_role() = 'admin'
      or public.is_org_owner(organization_id)
    )
  );

alter table public.agent_access enable row level security;

-- Read the assignment list: the agent owner, company admin/owner, or yourself.
drop policy if exists p_agent_access_read on public.agent_access;
create policy p_agent_access_read on public.agent_access
  for select using (
    public.is_org_member(organization_id)
    and (
      user_id = auth.uid()
      or public.is_agent_owner(agent_id)
      or public.current_app_role() = 'admin'
      or public.is_org_owner(organization_id)
    )
  );

-- Write assignments: the agent owner or company admin/owner.
drop policy if exists p_agent_access_write on public.agent_access;
create policy p_agent_access_write on public.agent_access
  for all using (
    public.is_org_member(organization_id)
    and (
      public.is_agent_owner(agent_id)
      or public.current_app_role() = 'admin'
      or public.is_org_owner(organization_id)
    )
  ) with check (
    public.is_org_member(organization_id)
    and (
      public.is_agent_owner(agent_id)
      or public.current_app_role() = 'admin'
      or public.is_org_owner(organization_id)
    )
  );

-- End of agent_access.sql


-- #####################################################################
-- STEP 07 / 16 — logos.sql
-- #####################################################################

-- =====================================================================
-- Per-tenant company logos. Run AFTER schema.sql.
--   * adds organizations.logo_url (public URL of the uploaded logo)
--   * creates a public Storage bucket for the image files
--
-- The bucket is PUBLIC READ (logos render via their public URL). Writes happen
-- ONLY through the service role in /api/admin/logo, which checks that the caller
-- is a global admin or an owner of that company — so no anon/authenticated write
-- policies are needed. Size + mime are also enforced at the storage layer.
-- =====================================================================

alter table public.organizations add column if not exists logo_url text;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('company-logos', 'company-logos', true, 1048576,
        array['image/png','image/jpeg','image/webp'])
on conflict (id) do nothing;

-- End of logos.sql


-- #####################################################################
-- STEP 08 / 16 — agent_runs.sql
-- #####################################################################

-- =====================================================================
-- agent_runs — history of agent executions. Run AFTER schema.sql.
--
-- Foundation for run history and the later trust features (citations,
-- confidence, hallucination feedback) — those columns are included now (nullable)
-- so no follow-up migration is needed when that phase lands.
-- =====================================================================

create table if not exists public.agent_runs (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  agent_id        uuid not null references public.agents(id) on delete cascade,
  user_id         uuid references public.profiles(id) on delete set null,
  kind            text not null default 'text',     -- 'text' | 'gmail'
  source          text,                              -- 'pasted' | 'txt' | 'pdf' | 'gmail'
  input           text,
  output          text,
  -- forward-compatible (trust phase): populated later
  confidence      numeric(4,3),
  citations       jsonb,
  accurate        boolean,
  hallucinated    boolean,
  rated_by        uuid references public.profiles(id) on delete set null,
  rated_at        timestamptz,
  created_at      timestamptz not null default now()
);
-- Idempotent in case the table already exists from an earlier run of this file.
alter table public.agent_runs add column if not exists source text;

create index if not exists idx_runs_org     on public.agent_runs(organization_id);
create index if not exists idx_runs_agent   on public.agent_runs(agent_id);
create index if not exists idx_runs_created on public.agent_runs(created_at);

alter table public.agent_runs enable row level security;

-- Read: you see your own runs; reviewers/admins see all org runs (mirrors sessions).
drop policy if exists p_runs_read on public.agent_runs;
create policy p_runs_read on public.agent_runs
  for select using (
    public.is_org_member(organization_id)
    and (user_id = auth.uid() or public.can_review())
  );

-- Insert: a member logs their own run.
drop policy if exists p_runs_insert on public.agent_runs;
create policy p_runs_insert on public.agent_runs
  for insert with check (
    public.is_org_member(organization_id) and user_id = auth.uid()
  );

-- Update (feedback, later): reviewers/admins only.
drop policy if exists p_runs_update on public.agent_runs;
create policy p_runs_update on public.agent_runs
  for update using (public.is_org_member(organization_id) and public.can_review());

-- End of agent_runs.sql


-- #####################################################################
-- STEP 09 / 16 — mission.sql
-- #####################################################################

-- =====================================================================
-- Per-company mission statement. Run AFTER schema.sql.
-- Same lightweight pattern as logos.sql (a nullable column on organizations).
-- =====================================================================

alter table public.organizations add column if not exists mission_statement text;
alter table public.organizations add column if not exists mission_headline text;

-- End of mission.sql


-- #####################################################################
-- STEP 10 / 16 — governance_kb.sql
-- #####################################################################

-- =====================================================================
-- Governance Knowledge Base (Phase A). Run AFTER schema.sql + provider_keys.sql
-- (the latter defines the is_org_owner helper reused below).
--
-- Distinct from the approval queue (governance_requests/approvals). This is the
-- org's guiding knowledge: company policies, best-practice docs, and which
-- pre-defined compliance packs a company has enabled. Per-tenant + RLS:
-- members READ, company admins/owners WRITE.
-- =====================================================================

-- ---- policies (company-authored rules) ----
create table if not exists public.policies (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  title           text not null,
  body            text,
  category        text,
  active          boolean not null default true,
  created_by      uuid references public.profiles(id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index if not exists idx_policies_org on public.policies(organization_id);

-- ---- best_practices (guidance docs/templates builders read) ----
create table if not exists public.best_practices (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  title           text not null,
  body            text,
  category        text,
  created_by      uuid references public.profiles(id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index if not exists idx_bp_org on public.best_practices(organization_id);

-- ---- compliance_packs (GLOBAL seeded catalog) ----
create table if not exists public.compliance_packs (
  id           uuid primary key default gen_random_uuid(),
  key          text not null unique,
  name         text not null,
  description  text,
  industry     text,
  requirements jsonb not null default '[]'::jsonb,
  created_at   timestamptz not null default now()
);

-- ---- org_compliance_packs (which packs a company enabled) ----
create table if not exists public.org_compliance_packs (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  pack_id         uuid not null references public.compliance_packs(id) on delete cascade,
  enabled_by      uuid references public.profiles(id) on delete set null,
  enabled_at      timestamptz not null default now(),
  unique (organization_id, pack_id)
);
create index if not exists idx_ocp_org on public.org_compliance_packs(organization_id);

-- updated_at maintenance (reuses the helper from schema.sql)
drop trigger if exists trg_touch_policies on public.policies;
create trigger trg_touch_policies before update on public.policies
  for each row execute function public.fn_touch_updated_at();
drop trigger if exists trg_touch_bp on public.best_practices;
create trigger trg_touch_bp before update on public.best_practices
  for each row execute function public.fn_touch_updated_at();

-- =====================================================================
-- RLS — members read; company admins (global admin OR org owner) write.
-- =====================================================================
alter table public.policies             enable row level security;
alter table public.best_practices       enable row level security;
alter table public.compliance_packs     enable row level security;
alter table public.org_compliance_packs enable row level security;

drop policy if exists p_policies_read on public.policies;
create policy p_policies_read on public.policies
  for select using (public.is_org_member(organization_id));
drop policy if exists p_policies_write on public.policies;
create policy p_policies_write on public.policies
  for all using (
    public.is_org_member(organization_id)
    and (public.current_app_role() = 'admin' or public.is_org_owner(organization_id))
  ) with check (
    public.is_org_member(organization_id)
    and (public.current_app_role() = 'admin' or public.is_org_owner(organization_id))
  );

drop policy if exists p_bp_read on public.best_practices;
create policy p_bp_read on public.best_practices
  for select using (public.is_org_member(organization_id));
drop policy if exists p_bp_write on public.best_practices;
create policy p_bp_write on public.best_practices
  for all using (
    public.is_org_member(organization_id)
    and (public.current_app_role() = 'admin' or public.is_org_owner(organization_id))
  ) with check (
    public.is_org_member(organization_id)
    and (public.current_app_role() = 'admin' or public.is_org_owner(organization_id))
  );

-- compliance_packs: global, read-only to any signed-in user (seeded via migration).
drop policy if exists p_packs_read on public.compliance_packs;
create policy p_packs_read on public.compliance_packs
  for select using (auth.uid() is not null);

drop policy if exists p_ocp_read on public.org_compliance_packs;
create policy p_ocp_read on public.org_compliance_packs
  for select using (public.is_org_member(organization_id));
drop policy if exists p_ocp_write on public.org_compliance_packs;
create policy p_ocp_write on public.org_compliance_packs
  for all using (
    public.is_org_member(organization_id)
    and (public.current_app_role() = 'admin' or public.is_org_owner(organization_id))
  ) with check (
    public.is_org_member(organization_id)
    and (public.current_app_role() = 'admin' or public.is_org_owner(organization_id))
  );

-- =====================================================================
-- Seed the compliance pack catalog.
-- =====================================================================
insert into public.compliance_packs (key, name, description, industry, requirements) values
  ('hipaa', 'HIPAA', 'US health data privacy & security (Health Insurance Portability and Accountability Act).', 'Healthcare',
   '["Never expose Protected Health Information (PHI) in outputs or logs","Encrypt PHI in transit and at rest","Maintain audit logs of all PHI access","Apply the minimum-necessary standard to data access","Require a Business Associate Agreement (BAA) with vendors handling PHI"]'::jsonb),
  ('ferpa', 'FERPA', 'US student education-records privacy (Family Educational Rights and Privacy Act).', 'Education',
   '["Do not disclose student education records without consent","Limit access to those with a legitimate educational interest","Allow students/parents to access and amend records","Log disclosures of education records"]'::jsonb),
  ('soc2', 'SOC 2', 'Trust Services Criteria: security, availability, processing integrity, confidentiality, privacy.', 'SaaS',
   '["Enforce least-privilege access controls","Maintain audit logging and monitoring","Encrypt sensitive data in transit and at rest","Follow a documented change-management process","Maintain an incident response plan"]'::jsonb),
  ('gdpr', 'GDPR', 'EU General Data Protection Regulation for personal data of EU residents.', 'Cross-industry',
   '["Process personal data only with a lawful basis","Honor data-subject rights (access, erasure, portability)","Apply data minimization and purpose limitation","Report personal-data breaches within 72 hours","Keep records of processing activities"]'::jsonb),
  ('ccpa', 'CCPA / CPRA', 'California Consumer Privacy Act / Privacy Rights Act consumer data rights.', 'Cross-industry',
   '["Disclose what personal information is collected and why","Honor opt-out of sale/sharing of personal information","Honor consumer rights to know, delete, and correct","Do not discriminate against consumers who exercise their rights"]'::jsonb)
on conflict (key) do nothing;

-- End of governance_kb.sql


-- #####################################################################
-- STEP 11 / 16 — knowledge_docs.sql
-- #####################################################################

-- =====================================================================
-- Knowledge documents (uploaded PDFs / Word .docx). Run AFTER governance_kb.sql.
-- The app extracts text server-side and stores it here; the "Sync knowledge"
-- action then chunks + embeds it into knowledge_chunks for RAG. Per-tenant + RLS
-- (members read, company admins/owners write).
-- =====================================================================

create table if not exists public.knowledge_documents (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  title           text not null,
  filename        text,
  content         text,                 -- extracted plain text
  created_by      uuid references public.profiles(id) on delete set null,
  created_at      timestamptz not null default now()
);
create index if not exists idx_kdocs_org on public.knowledge_documents(organization_id);

alter table public.knowledge_documents enable row level security;

drop policy if exists p_kdocs_read on public.knowledge_documents;
create policy p_kdocs_read on public.knowledge_documents
  for select using (public.is_org_member(organization_id));

drop policy if exists p_kdocs_write on public.knowledge_documents;
create policy p_kdocs_write on public.knowledge_documents
  for all using (
    public.is_org_member(organization_id)
    and (public.current_app_role() = 'admin' or public.is_org_owner(organization_id))
  ) with check (
    public.is_org_member(organization_id)
    and (public.current_app_role() = 'admin' or public.is_org_owner(organization_id))
  );

-- End of knowledge_docs.sql


-- #####################################################################
-- STEP 12 / 16 — rag.sql
-- #####################################################################

-- =====================================================================
-- RAG grounding (pgvector). Run AFTER governance_kb.sql.
--
-- Provider-agnostic embeddings at 768 dims: Google text-embedding-004 (native
-- 768) or OpenAI text-embedding-3-small (reduced to 768). Per-tenant + RLS.
-- SAFE TO RE-RUN — it (re)creates the embedding column at 768. (If you ran an
-- earlier 1536-dim version, just re-run this file, then click "Sync knowledge".)
-- =====================================================================

create extension if not exists vector;

create table if not exists public.knowledge_chunks (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  source_type     text not null,            -- 'policy' | 'best_practice' | 'compliance'
  source_title    text not null,
  content         text not null,
  created_at      timestamptz not null default now()
);
create index if not exists idx_kchunks_org on public.knowledge_chunks(organization_id);

-- (Re)create the embedding column at 768 dims. Dropping it is safe — chunks are
-- rebuilt from scratch by the "Sync knowledge" action.
drop index if exists public.idx_kchunks_embedding;
alter table public.knowledge_chunks drop column if exists embedding;
alter table public.knowledge_chunks add column embedding vector(768);
create index idx_kchunks_embedding on public.knowledge_chunks
  using hnsw (embedding vector_cosine_ops);

alter table public.knowledge_chunks enable row level security;

drop policy if exists p_kchunks_read on public.knowledge_chunks;
create policy p_kchunks_read on public.knowledge_chunks
  for select using (public.is_org_member(organization_id));

drop policy if exists p_kchunks_write on public.knowledge_chunks;
create policy p_kchunks_write on public.knowledge_chunks
  for all using (
    public.is_org_member(organization_id)
    and (public.current_app_role() = 'admin' or public.is_org_owner(organization_id))
  ) with check (
    public.is_org_member(organization_id)
    and (public.current_app_role() = 'admin' or public.is_org_owner(organization_id))
  );

-- Cosine-similarity retrieval. SECURITY INVOKER (default) so RLS on
-- knowledge_chunks still applies — a caller only matches their own org's chunks.
-- Param declared as bare `vector` so it accepts whatever dimension is in use.
create or replace function public.match_knowledge(query_embedding vector, org uuid, match_count int)
returns table (id uuid, content text, source_type text, source_title text, similarity float)
language sql stable as $$
  select kc.id, kc.content, kc.source_type, kc.source_title,
         1 - (kc.embedding <=> query_embedding) as similarity
  from public.knowledge_chunks kc
  where kc.organization_id = org and kc.embedding is not null
  order by kc.embedding <=> query_embedding
  limit match_count;
$$;

grant execute on function public.match_knowledge(vector, uuid, int) to authenticated;

-- End of rag.sql


-- #####################################################################
-- STEP 13 / 16 — rag_incremental.sql
-- #####################################################################

-- =====================================================================
-- Incremental RAG re-indexing. Run AFTER rag.sql.
-- Adds source_id so a single knowledge item's chunks can be replaced on edit
-- (auto-reindex) without rebuilding the whole corpus. Non-destructive.
-- After running this, click "Sync knowledge" once to backfill source_id on
-- existing chunks; thereafter edits re-embed automatically.
-- =====================================================================

alter table public.knowledge_chunks add column if not exists source_id uuid;
create index if not exists idx_kchunks_source on public.knowledge_chunks(source_id);

-- End of rag_incremental.sql


-- #####################################################################
-- STEP 14 / 16 — deletes.sql
-- #####################################################################

-- =====================================================================
-- Delete permissions for agents & apps (run AFTER schema.sql + apps.sql)
--
-- Admin/builder deletes ALREADY work via the existing p_agents_write /
-- p_apps_write "for all" policies — you do NOT need this file for those.
-- This OPTIONAL migration additionally lets a non-admin OWNER delete their own
-- item: an agent's owner_id, or an app's product_owner. Permissive policies are
-- OR'd with the existing ones, so the effective rule becomes:
--   member of the org AND (admin/builder OR you own the item).
-- Tenant isolation still holds (is_org_member) and FK cascades clean up children.
-- =====================================================================

drop policy if exists p_agents_delete on public.agents;
create policy p_agents_delete on public.agents
  for delete using (
    public.is_org_member(organization_id)
    and (public.current_app_role() in ('admin','builder') or owner_id = auth.uid())
  );

drop policy if exists p_apps_delete on public.apps;
create policy p_apps_delete on public.apps
  for delete using (
    public.is_org_member(organization_id)
    and (public.current_app_role() in ('admin','builder') or product_owner = auth.uid())
  );

-- End of deletes.sql


-- #####################################################################
-- STEP 15 / 16 — accounts.sql
-- #####################################################################

-- =====================================================================
-- Accounts → Workspaces hierarchy  (ADDITIVE migration)
--
-- RUN ORDER: this file must run AFTER all of:
--   schema.sql, provider_keys.sql, apps.sql, governance_kb.sql,
--   knowledge_docs.sql, agent_access.sql, agent_runs.sql
-- because it OVERRIDES several policies first defined there (to add the
-- account-admin rollup) and reuses their helpers (is_org_owner, etc.).
--
-- THE MODEL
--   accounts ............ the customer / billing entity (a holding company or a
--                         single company). Lead Ventures is an account.
--   organizations ....... unchanged physical table, now a "WORKSPACE" under an
--                         account (organizations.account_id). A subsidiary.
--   account_members ..... account admins (e.g. Sean) — the ROLLUP principal who
--                         sees/manages every workspace in the account.
--   org_members ......... unchanged — the per-person ↔ per-workspace assignment.
--   policy_workspaces ... account policy ↔ which workspaces it applies to.
--
-- SECURITY MODEL (enforced by RLS below)
--   * Absolute account-to-account isolation (unchanged).
--   * Per-person workspace assignment: a member sees only workspaces they have
--     an org_members row for.
--   * Account-admin rollup: an account admin sees/manages every workspace whose
--     organizations.account_id they administer — and NOTHING outside it.
--   * The single chokepoint is_org_member(org) is redefined to include the
--     rollup, so all 22 tenant tables inherit it consistently.
--   * An account may have ZERO own workspaces (a pure holding company) or its
--     own workspace(s) (a holding company that also does operational work).
-- =====================================================================

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------
-- ENUM
-- ---------------------------------------------------------------------
do $$ begin
  create type account_role as enum ('owner', 'admin');
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------
-- TABLES
-- ---------------------------------------------------------------------
create table if not exists public.accounts (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  slug        text not null unique,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.account_members (
  id           uuid primary key default gen_random_uuid(),
  account_id   uuid not null references public.accounts(id) on delete cascade,
  user_id      uuid not null references public.profiles(id) on delete cascade,
  account_role account_role not null default 'admin',
  created_at   timestamptz not null default now(),
  unique (account_id, user_id)
);
create index if not exists idx_account_members_user on public.account_members(user_id);
create index if not exists idx_account_members_acct on public.account_members(account_id);

-- Workspaces (organizations) gain a parent account. Nullable so the additive
-- migration never fails on pre-existing rows; the app always sets it on create.
-- ON DELETE CASCADE: deleting an account removes its workspaces (and, via the
-- existing per-table cascades, their data) — intentional for tenant teardown.
alter table public.organizations
  add column if not exists account_id uuid references public.accounts(id) on delete cascade;
create index if not exists idx_org_account on public.organizations(account_id);

-- Policies become EITHER account-level (authored at the account, mapped to
-- workspaces via policy_workspaces) OR workspace-local (the original behavior).
alter table public.policies
  add column if not exists account_id uuid references public.accounts(id) on delete cascade;
alter table public.policies alter column organization_id drop not null;
do $$ begin
  alter table public.policies add constraint policies_scope_chk
    check ((account_id is not null)::int + (organization_id is not null)::int = 1);
exception when duplicate_object then null; end $$;
create index if not exists idx_policies_account on public.policies(account_id);

-- The account-admin's governance mapping: which workspaces an account policy
-- applies to (all / several / one). Workspace-local policies do NOT use this.
create table if not exists public.policy_workspaces (
  id              uuid primary key default gen_random_uuid(),
  policy_id       uuid not null references public.policies(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  created_at      timestamptz not null default now(),
  unique (policy_id, organization_id)
);
create index if not exists idx_pw_policy on public.policy_workspaces(policy_id);
create index if not exists idx_pw_org    on public.policy_workspaces(organization_id);

-- updated_at maintenance (reuses fn_touch_updated_at from schema.sql)
drop trigger if exists trg_touch_accounts on public.accounts;
create trigger trg_touch_accounts before update on public.accounts
  for each row execute function public.fn_touch_updated_at();

-- =====================================================================
-- HELPER FUNCTIONS  (all SECURITY DEFINER to avoid RLS recursion)
-- =====================================================================

-- Direct workspace membership — the ORIGINAL is_org_member body, preserved so
-- the redefined is_org_member can still ask "is this a direct member?".
create or replace function public.is_workspace_member(org uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.org_members m
    where m.organization_id = org and m.user_id = auth.uid()
  );
$$;

-- Is the current user an admin (any role) of this account?
create or replace function public.is_account_admin(acct uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.account_members am
    where am.account_id = acct and am.user_id = auth.uid()
  );
$$;

-- Is the current user an OWNER of this account? (manage members/structure)
create or replace function public.is_account_owner(acct uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.account_members am
    where am.account_id = acct and am.user_id = auth.uid() and am.account_role = 'owner'
  );
$$;

-- Does the current user administer the ACCOUNT that owns this workspace?
-- This is the rollup predicate and the cross-account guard in one: it only
-- matches workspaces whose organizations.account_id the user administers.
create or replace function public.is_account_admin_of_workspace(org uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1
    from public.organizations o
    join public.account_members am on am.account_id = o.account_id
    where o.id = org and am.user_id = auth.uid()
  );
$$;

-- THE SINGLE CHOKEPOINT. Every tenant table's RLS calls this. Redefined to mean
-- "direct member of the workspace OR account admin of its parent account".
-- Direct member  → per-person workspace assignment.
-- Account admin  → rollup across the account's workspaces.
-- Neither        → no access (absolute isolation, incl. between sibling
--                  workspaces and between accounts).
create or replace function public.is_org_member(org uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select public.is_workspace_member(org) or public.is_account_admin_of_workspace(org);
$$;

-- Cross-table lookups for the policies / policy_workspaces RLS. These MUST be
-- SECURITY DEFINER (bypass RLS) so the two tables' policies can reference each
-- other through a function call without triggering mutual RLS recursion.
create or replace function public.account_of_policy(p_id uuid)
returns uuid language sql stable security definer set search_path = public as $$
  select account_id from public.policies where id = p_id;
$$;

create or replace function public.account_of_workspace(org uuid)
returns uuid language sql stable security definer set search_path = public as $$
  select account_id from public.organizations where id = org;
$$;

-- Is the current user a member of any workspace this account policy is mapped to?
create or replace function public.policy_assigned_to_member(p_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.policy_workspaces pw
    where pw.policy_id = p_id and public.is_workspace_member(pw.organization_id)
  );
$$;

-- =====================================================================
-- RLS — new tables
-- =====================================================================
alter table public.accounts          enable row level security;
alter table public.account_members   enable row level security;
alter table public.policy_workspaces enable row level security;

-- accounts: readable by an admin of the account OR a member of any workspace
-- under it (so workspace users can resolve their account name/branding).
drop policy if exists p_accounts_read on public.accounts;
create policy p_accounts_read on public.accounts
  for select using (
    public.is_account_admin(id)
    or exists (
      select 1 from public.organizations o
      where o.account_id = accounts.id and public.is_workspace_member(o.id)
    )
  );
-- Structural writes (create/rename/delete accounts) happen via the service role
-- in the super-admin portal; from a user session, only an account OWNER may.
drop policy if exists p_accounts_write on public.accounts;
create policy p_accounts_write on public.accounts
  for all using (public.is_account_owner(id)) with check (public.is_account_owner(id));

-- account_members: an account admin sees the roster; everyone sees their own row.
drop policy if exists p_account_members_read on public.account_members;
create policy p_account_members_read on public.account_members
  for select using (public.is_account_admin(account_id) or user_id = auth.uid());
-- Only an account OWNER may add/remove account admins (prevents self-promotion;
-- the super-admin portal does the initial seed via the service role).
drop policy if exists p_account_members_write on public.account_members;
create policy p_account_members_write on public.account_members
  for all using (public.is_account_owner(account_id)) with check (public.is_account_owner(account_id));

-- policy_workspaces: readable by a member of the mapped workspace or an admin of
-- the policy's account. Writable ONLY by an admin of the policy's account AND
-- ONLY when the target workspace belongs to that SAME account — the cross-account
-- governance guard (you can never map a policy onto another account's workspace).
-- Reference policies only through SECURITY DEFINER helpers (account_of_policy /
-- account_of_workspace) — never a direct subquery into policies — so there is no
-- mutual RLS recursion with p_policies_read.
drop policy if exists p_pw_read on public.policy_workspaces;
create policy p_pw_read on public.policy_workspaces
  for select using (
    public.is_workspace_member(organization_id)
    or public.is_account_admin(public.account_of_policy(policy_id))
  );
drop policy if exists p_pw_write on public.policy_workspaces;
create policy p_pw_write on public.policy_workspaces
  for all using (
    public.account_of_policy(policy_id) is not null
    and public.is_account_admin(public.account_of_policy(policy_id))
    and public.account_of_workspace(organization_id) = public.account_of_policy(policy_id)
  ) with check (
    public.account_of_policy(policy_id) is not null
    and public.is_account_admin(public.account_of_policy(policy_id))
    and public.account_of_workspace(organization_id) = public.account_of_policy(policy_id)
  );

-- =====================================================================
-- RLS — OVERRIDES of existing policies to grant the account-admin rollup.
-- Each adds `OR public.is_account_admin_of_workspace(organization_id)` to the
-- privileged branch so an account admin has workspace-admin powers inside their
-- account's workspaces. (Reads already flow through the redefined is_org_member;
-- these overrides cover the RBAC-gated WRITES and the restricted-agent READ.)
-- =====================================================================

-- organizations: members who are app-admins write; account admins also write.
drop policy if exists p_org_write on public.organizations;
create policy p_org_write on public.organizations
  for update using (
    (public.is_org_member(id) and public.current_app_role() = 'admin')
    or public.is_account_admin_of_workspace(id)
  );

-- agents READ (restricted-aware; overrides agent_access.sql): account admins see
-- every agent in their workspaces, including 'restricted' ones.
drop policy if exists p_agents_read on public.agents;
create policy p_agents_read on public.agents
  for select using (
    public.is_org_member(organization_id)
    and (
      visibility = 'everyone'
      or owner_id = auth.uid()
      or public.has_agent_access(id)
      or public.current_app_role() = 'admin'
      or public.is_org_owner(organization_id)
      or public.is_account_admin_of_workspace(organization_id)
    )
  );

-- agents WRITE
drop policy if exists p_agents_write on public.agents;
create policy p_agents_write on public.agents
  for all using (
    public.is_org_member(organization_id)
    and (public.current_app_role() in ('admin','builder')
         or public.is_account_admin_of_workspace(organization_id))
  ) with check (
    public.is_org_member(organization_id)
    and (public.current_app_role() in ('admin','builder')
         or public.is_account_admin_of_workspace(organization_id))
  );

-- agent_versions WRITE
drop policy if exists p_versions_write on public.agent_versions;
create policy p_versions_write on public.agent_versions
  for all using (
    public.is_org_member(organization_id)
    and (public.current_app_role() in ('admin','builder')
         or public.is_account_admin_of_workspace(organization_id))
  ) with check (
    public.is_org_member(organization_id)
    and (public.current_app_role() in ('admin','builder')
         or public.is_account_admin_of_workspace(organization_id))
  );

-- apps WRITE
drop policy if exists p_apps_write on public.apps;
create policy p_apps_write on public.apps
  for all using (
    public.is_org_member(organization_id)
    and (public.current_app_role() in ('admin','builder')
         or public.is_account_admin_of_workspace(organization_id))
  ) with check (
    public.is_org_member(organization_id)
    and (public.current_app_role() in ('admin','builder')
         or public.is_account_admin_of_workspace(organization_id))
  );

-- governance_requests UPDATE (resolve/triage)
drop policy if exists p_gov_update on public.governance_requests;
create policy p_gov_update on public.governance_requests
  for update using (
    public.is_org_member(organization_id)
    and (public.can_review() or public.is_account_admin_of_workspace(organization_id))
  );

-- approvals INSERT (record a decision)
drop policy if exists p_approvals_write on public.approvals;
create policy p_approvals_write on public.approvals
  for insert with check (
    public.is_org_member(organization_id)
    and (public.can_review() or public.is_account_admin_of_workspace(organization_id))
  );

-- best_practices WRITE
drop policy if exists p_bp_write on public.best_practices;
create policy p_bp_write on public.best_practices
  for all using (
    public.is_org_member(organization_id)
    and (public.current_app_role() = 'admin' or public.is_org_owner(organization_id)
         or public.is_account_admin_of_workspace(organization_id))
  ) with check (
    public.is_org_member(organization_id)
    and (public.current_app_role() = 'admin' or public.is_org_owner(organization_id)
         or public.is_account_admin_of_workspace(organization_id))
  );

-- org_compliance_packs WRITE (assign/unassign a pack to a workspace)
drop policy if exists p_ocp_write on public.org_compliance_packs;
create policy p_ocp_write on public.org_compliance_packs
  for all using (
    public.is_org_member(organization_id)
    and (public.current_app_role() = 'admin' or public.is_org_owner(organization_id)
         or public.is_account_admin_of_workspace(organization_id))
  ) with check (
    public.is_org_member(organization_id)
    and (public.current_app_role() = 'admin' or public.is_org_owner(organization_id)
         or public.is_account_admin_of_workspace(organization_id))
  );

-- knowledge_documents WRITE
drop policy if exists p_kdocs_write on public.knowledge_documents;
create policy p_kdocs_write on public.knowledge_documents
  for all using (
    public.is_org_member(organization_id)
    and (public.current_app_role() = 'admin' or public.is_org_owner(organization_id)
         or public.is_account_admin_of_workspace(organization_id))
  ) with check (
    public.is_org_member(organization_id)
    and (public.current_app_role() = 'admin' or public.is_org_owner(organization_id)
         or public.is_account_admin_of_workspace(organization_id))
  );

-- agent_access READ + WRITE (manage restricted-agent grants)
drop policy if exists p_agent_access_read on public.agent_access;
create policy p_agent_access_read on public.agent_access
  for select using (
    public.is_org_member(organization_id)
    and (
      user_id = auth.uid()
      or public.is_agent_owner(agent_id)
      or public.current_app_role() = 'admin'
      or public.is_org_owner(organization_id)
      or public.is_account_admin_of_workspace(organization_id)
    )
  );
drop policy if exists p_agent_access_write on public.agent_access;
create policy p_agent_access_write on public.agent_access
  for all using (
    public.is_org_member(organization_id)
    and (
      public.is_agent_owner(agent_id)
      or public.current_app_role() = 'admin'
      or public.is_org_owner(organization_id)
      or public.is_account_admin_of_workspace(organization_id)
    )
  ) with check (
    public.is_org_member(organization_id)
    and (
      public.is_agent_owner(agent_id)
      or public.current_app_role() = 'admin'
      or public.is_org_owner(organization_id)
      or public.is_account_admin_of_workspace(organization_id)
    )
  );

-- =====================================================================
-- RLS — policies: the account/local SPLIT (assignable governance)
-- =====================================================================

-- READ: a workspace member reads local policies of their workspace AND account
-- policies MAPPED to their workspace; an account admin reads all their account's
-- policies. Account policies mapped to OTHER workspaces stay hidden.
-- Reference policy_workspaces only through the SECURITY DEFINER helper
-- policy_assigned_to_member — never a direct subquery — to avoid mutual RLS
-- recursion with p_pw_read.
drop policy if exists p_policies_read on public.policies;
create policy p_policies_read on public.policies
  for select using (
    (organization_id is not null and public.is_org_member(organization_id))
    or (
      account_id is not null and (
        public.is_account_admin(account_id)
        or public.policy_assigned_to_member(id)
      )
    )
  );

-- WRITE: workspace-local policies follow the original rule (+ account-admin
-- escape); account-level policies are writable only by an admin of that account.
drop policy if exists p_policies_write on public.policies;
create policy p_policies_write on public.policies
  for all using (
    (organization_id is not null and public.is_org_member(organization_id)
      and (public.current_app_role() = 'admin' or public.is_org_owner(organization_id)
           or public.is_account_admin_of_workspace(organization_id)))
    or (account_id is not null and public.is_account_admin(account_id))
  ) with check (
    (organization_id is not null and public.is_org_member(organization_id)
      and (public.current_app_role() = 'admin' or public.is_org_owner(organization_id)
           or public.is_account_admin_of_workspace(organization_id)))
    or (account_id is not null and public.is_account_admin(account_id))
  );

-- =====================================================================
-- Convenience view: a workspace's EFFECTIVE policies (local ∪ account-assigned).
-- RLS on the base table still applies through the view (security_invoker).
-- =====================================================================
drop view if exists public.v_workspace_policies;
create view public.v_workspace_policies
  with (security_invoker = true) as
  select o.id            as workspace_id,
         p.id            as policy_id,
         p.title,
         p.body,
         p.category,
         p.active,
         p.account_id,
         p.organization_id,
         (p.account_id is not null) as is_account_policy,
         p.created_at
  from public.organizations o
  join public.policies p
    on (p.organization_id = o.id)
    or (p.account_id is not null and exists (
          select 1 from public.policy_workspaces pw
          where pw.policy_id = p.id and pw.organization_id = o.id));

-- End of accounts.sql


-- #####################################################################
-- STEP 16 / 16 — accounts_fix_recursion.sql
-- #####################################################################

-- =====================================================================
-- FIX: infinite recursion between policies and policy_workspaces RLS.
--
-- The original accounts.sql had p_policies_read subquery into policy_workspaces,
-- while p_pw_read / p_pw_write subqueried back into policies — a mutual RLS
-- reference that Postgres rejects as "infinite recursion detected in policy for
-- relation policies".
--
-- Fix: move every cross-table lookup into SECURITY DEFINER helpers (which run as
-- the table owner and bypass RLS, so they don't re-trigger the other table's
-- policy). The policies / policy_workspaces policies then reference only function
-- calls, never each other's table directly. Idempotent — safe to run once on an
-- existing database. Run AFTER accounts.sql.
-- =====================================================================

-- account_id of a policy (bypasses policies RLS → no recursion).
create or replace function public.account_of_policy(p_id uuid)
returns uuid language sql stable security definer set search_path = public as $$
  select account_id from public.policies where id = p_id;
$$;

-- account_id of a workspace.
create or replace function public.account_of_workspace(org uuid)
returns uuid language sql stable security definer set search_path = public as $$
  select account_id from public.organizations where id = org;
$$;

-- Is the current user a member of any workspace this account policy is mapped to?
-- Reads policy_workspaces inside a definer fn, so it does NOT invoke that table's RLS.
create or replace function public.policy_assigned_to_member(p_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.policy_workspaces pw
    where pw.policy_id = p_id and public.is_workspace_member(pw.organization_id)
  );
$$;

-- ---- policies READ: no direct reference to policy_workspaces ----
drop policy if exists p_policies_read on public.policies;
create policy p_policies_read on public.policies
  for select using (
    (organization_id is not null and public.is_org_member(organization_id))
    or (
      account_id is not null and (
        public.is_account_admin(account_id)
        or public.policy_assigned_to_member(id)
      )
    )
  );

-- ---- policy_workspaces READ: no direct reference to policies ----
drop policy if exists p_pw_read on public.policy_workspaces;
create policy p_pw_read on public.policy_workspaces
  for select using (
    public.is_workspace_member(organization_id)
    or public.is_account_admin(public.account_of_policy(policy_id))
  );

-- ---- policy_workspaces WRITE: account-admin of the policy's account, and the
--       target workspace must belong to that SAME account (cross-account guard) ----
drop policy if exists p_pw_write on public.policy_workspaces;
create policy p_pw_write on public.policy_workspaces
  for all using (
    public.account_of_policy(policy_id) is not null
    and public.is_account_admin(public.account_of_policy(policy_id))
    and public.account_of_workspace(organization_id) = public.account_of_policy(policy_id)
  ) with check (
    public.account_of_policy(policy_id) is not null
    and public.is_account_admin(public.account_of_policy(policy_id))
    and public.account_of_workspace(organization_id) = public.account_of_policy(policy_id)
  );

-- End of accounts_fix_recursion.sql


